name: Setup PKL CLI and run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Organism module
        uses: drafteame/pkl-action@main
        with:
          version: '0.1.3'  # Specify the desired version here
          args: 'test tests/Organism.pkl'    # Specify the command arguments here

      - name: Test Workflow module
        uses: drafteame/pkl-action@main
        with:
          version: '0.1.3'
          args: 'test tests/Workflow.pkl'
